#!/bin/sh
cat << EOF > .env
FILES_ROOT_PATH=/app
PORT=5000
DB_HOST=db
DB_PORT=3306
DB_USER=root
DB_PASSWORD=
DB_NAME=fair_journal
URL=http://localhost:5000/
SHOW_LOGS=true
TON_STORAGE_BIN_PATH=/app/storage-daemon-cli-linux-arm64
TON_STORAGE_HOST=127.0.0.1:5555
TON_STORAGE_DATABASE_PATH=/app/storage-db
TON_STORAGE_TIMEOUT=5000
TON_STORAGE_WAIT_ATTEMPTS=3
TON_STORAGE_CHECK_WAIT_TIMEOUT=1000
EOF
