version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fair_journal
      MYSQL_USER: fjuser
      MYSQL_PASSWORD: fjpassword
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
